### ISSUE TITLE
No support for HTTPProvider

### ISSUE THREAD

**Issue by s2r3dswq** [medvedev1088/ethereum-etl#12]
would be great to connect by JSON RPC.

**Comment by medvedev1088** [comment]
Yes, I'm going to fully migrate to web3.py once they support batch requests https://github.com/ethereum/web3.py/issues/832. Please upvote that issue.

Once I do this all their providers will be supported, including HTTPProvider, WebsocketProvider, IPCProvider. 

At this point only exporting ERC20 transfers uses web3.py so adding support for more providers should be fairly easy for ERC20 transfers. For blocks and transactions I'd need to do some copy pasting.

**Comment by medvedev1088** [comment]
Fixed https://github.com/medvedev1088/ethereum-etl/pull/55
