### ISSUE TITLE
Add support for eth_getTransactionReceipt command

### ISSUE THREAD

**Issue by tokusyu** [medvedev1088/ethereum-etl#26]
I would like to get a value of "gasUsed" in each transactions at the same time as Blocks and Transactions data exporting.
I think adding support of JSON RPC "eth_getTransactionReceipt" is the best way to get this information, but is it possible to implement to this ETL tool?

**Comment by tokusyu** [comment]
Thanks for your reply.
I thank that trasactions.tx_gas and transaction_receipt.gas_used are not same.
https://github.com/ethereum/go-ethereum/issues/1097

So I want support of eth_getTransactionReceipt in this ETL tool.

Sincerely 


2018/06/20 0:44、medvedev1088 <notifications@github.com>のメール:

**Comment by medvedev1088** [comment]
You are right, they are different fields.

Here is how it could be added to export_blocks_job.py:

```
    def _export_batch(self, batch_start, batch_end):
        blocks_rpc = list(generate_get_block_by_number_json_rpc(batch_start, batch_end, self.export_transactions))
        response = self.ipc_wrapper.make_request(json.dumps(blocks_rpc))

        blocks = [self.block_mapper.json_dict_to_block(response_item['result']) for response_item in response]

        for block in blocks:
            self._export_block(block)

        transactions_hashes = [tx.hash for tx in block.transactions for block in block]
        if export_receipts:
            receipts_rpc = list(generate_get_receipt_by_tx_hash_json_rpc(transactions_hashes))
            response = self.ipc_wrapper.make_request(json.dumps(receipts_rpc))
            export_receipts(response)
```

**Comment by medvedev1088** [comment]
@tokusyu please help upvote this feature request https://github.com/ethereum/go-ethereum/issues/17044. It will be much easier to export receipts with this change.

**Comment by medvedev1088** [comment]
@tokusyu I added support for receipts and logs https://github.com/medvedev1088/ethereum-etl#command-reference. Please help test if you have a chance. 

I also uploaded receipts and logs to the public dataset on BigQuery https://medium.com/@medvedev1088/ethereum-blockchain-on-google-bigquery-283fb300f579

**Comment by tokusyu** [comment]
Thanks.
I tested it and It worked like a charm.
