### ISSUE TITLE
Missing Transfers With export_token_transfers.py

### ISSUE THREAD

**Issue by Mushoz** [medvedev1088/ethereum-etl#78]
I am trying to fetch all erc-20 tokens that have ever been made for each specific token with export_token_transfers.py. However, I am unable to get all transfers successfully. I am using the following command to export the transfers:

python3 export_token_transfers.py --start-block 0 --end-block 6123389 --provider-uri file:///home/jaap/.local/share/io.parity.ethereum/jsonrpc.ipc --output ../Documents/transfers.csv

However, I am only seeing transfers from block 6110001 and later. Is this a bug somehow with these ETL scripts? Or more likely, does this have something to do with the fact my Parity Node was warp synced?

**Comment by medvedev1088** [comment]
Most likely it's related to Parity's warp sync. Here is what the documentation says https://wiki.parity.io/Getting-Synced:

> Note, at present, snapshotting does not place all of the block or receipt data into the database. This means **you will not get information relating to transactions more than a few days old**. This is fine for some usages such as mining, but if you have or need access to historical transaction data (e.g. if you have an account that you’ve been using with Geth and wish to browse sent transactions) then you probably want to sync normally.
> 
> To disable snapshotting, run Parity with:
> 
> $ parity --no-warp

ERC20 transfers are extracted from transaction receipts which are missing in warp mode. Try either `parity --no-warp` or `geth`.

**Comment by Mushoz** [comment]
For future reference for people running into the same issue: I just synced the first ~1 million blocks without warp sync and can indeed confirm that I now do see erc-20 transfer events. Thank you very much for your insanely fast reply and the wonderful piece of software!
