### ISSUE TITLE
Date based hive partition is more useful than Block No. based in analyzing.

### ISSUE THREAD

**Issue by tokusyu** [medvedev1088/ethereum-etl#80]
Recently I’ve been analyzing Ethereum block chain data and found that the Block No. based partions didn’t benefit me.
I think the Block No. based partition is useful only when a query exactly fits the start_block and end_block and it didn’t occur in my situation, but querying by dates was occurred so often.
So I would like suggest that export_all.sh and related schemes should be refactored by Date based partition using “get_block_range_for_date.py”

**Comment by medvedev1088** [comment]
Totally agree with you. Partitioning by date is much more convenient.

**Comment by tokusyu** [comment]
Could I upload AWS schemas for partition by date?

**Comment by medvedev1088** [comment]
Sure, go ahead, it will be useful to other people also.
