### ISSUE TITLE
Data_dir

### ISSUE THREAD

**Issue by fadetogray** [medvedev1088/ethereum-etl#81]
I just want to use an external data storage (my nas server), but unfortunately I do not understand how to add a data dir folder.

As far as I understand, there are no keys to specifying a specific directory.

**Comment by medvedev1088** [comment]
Do you mean the output directory for the CSV files? You can use `-o` option for `export_all.sh`

**Comment by fadetogray** [comment]
No, I mean Ethereum directory --provider-uri file://blah/blah/Ethereum/geth.ipc

**Comment by medvedev1088** [comment]
You can just specify the path to the ipc file. For example if you started geth with datadir=/my/custom/dir, the ipc file will probably be somewhere at /my/custom/dir/geth.ipc. Then you start the script with 

--provider-uri file:///my/custom/dir/geth.ipc

**Comment by medvedev1088** [comment]
Notice the 3 slashes `file///`

**Comment by fadetogray** [comment]
Oh yes! But there is a small condition. I should use these senttings:

Run ethereum as

geth --cache=2048 --datadir "/Volumes/Blah.Blah/Ethereum" --ipcpath "~/Library/Ethereum/geth.ipc"

And run scripts as

.... file://$HOME/Library/Ethereum/geth.ipc ...

Thanks for your thoughts!
